import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Providers from "@/components/Providers";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/auth";

import NextTopLoader from 'nextjs-toploader';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SIPAKER PNP",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Ambil session di sisi server (lebih cepat & aman)
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextTopLoader 
          color="#2563eb" // Warna Biru (sesuai tema sipaker)
          height={3}
          showSpinner={false} // Matikan spinner pojok kanan (opsional)
        />
        <Providers session={session}>
          {children}
        </Providers>
      </body>
    </html>
  );
}
